# Shared resoruce limits definition
x-deploy: &default-resources
  deploy:
    resources:
      limits:
        memory: 3G
        cpus: "6.0"

services:
  pagerank-facebook:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/pagerank
      - DATASET=data/ego-Facebook/facebook_combined.txt
      - OUTPUT_FILE=pagerank-facebook
    command: sh run.sh
    <<: *default-resources

  pagerank-epinions1:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/pagerank
      - DATASET=data/soc-Epinions1/soc-Epinions1.txt
      - OUTPUT_FILE=pagerank-epinions1
    command: sh run.sh
    <<: *default-resources

  pagerank-google:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/pagerank
      - DATASET=data/web-Google/web-Google.txt
      - OUTPUT_FILE=pagerank-google
    command: sh run.sh
    <<: *default-resources

  connectedcomponents-facebook:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/connectedcomponents
      - DATASET=data/ego-Facebook/facebook_combined.txt
      - OUTPUT_FILE=connectedcomponents-facebook
    command: sh run.sh
    <<: *default-resources

  connectedcomponents-epinions1:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/connectedcomponents
      - DATASET=data/soc-Epinions1/soc-Epinions1.txt
      - OUTPUT_FILE=connectedcomponents-epinions1
    command: sh run.sh
    <<: *default-resources

  connectedcomponents-google:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/connectedcomponents
      - DATASET=data/web-Google/web-Google.txt
      - OUTPUT_FILE=connectedcomponents-google
    command: sh run.sh
    <<: *default-resources

  trianglecounting-facebook:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/trianglecounting
      - DATASET=data/ego-Facebook/facebook_combined.txt
      - OUTPUT_FILE=trianglecounting-facebook
    command: sh run.sh
    <<: *default-resources

  trianglecounting-epinions1:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/trianglecounting
      - DATASET=data/soc-Epinions1/soc-Epinions1.txt
      - OUTPUT_FILE=trianglecounting-epinions1
    command: sh run.sh
    <<: *default-resources

  trianglecounting-google:
    build: ./graphchi-c/
    volumes:
      - ./output:/home/ubuntu/output
    environment: 
      - EXECUTABLE=bin/example_apps/trianglecounting
      - DATASET=data/web-Google/web-Google.txt
      - OUTPUT_FILE=trianglecounting-google
    command: sh run.sh
    <<: *default-resources
