services:
  pagerank-facebook:
    build: ./graphchi-c/
    command: "bin/example_apps/pagerank file data/ego-Facebook/facebook_combined.txt filetype edgelist niters 100"

  pagerank-epinions1:
    build: ./graphchi-c/
    command: "bin/example_apps/pagerank file data/soc-Epinions1/soc-Epinions1.txt filetype edgelist niters 100"

  pagerank-google:
    build: ./graphchi-c/
    command: "bin/example_apps/pagerank file data/web-Google/web-Google.txt filetype edgelist niters 100"

  connectedcomponents-facebook:
    build: ./graphchi-c/
    command: "bin/example_apps/connectedcomponents file data/ego-Facebook/facebook_combined.txt filetype edgelist"

  connectedcomponents-epinions1:
    build: ./graphchi-c/
    command: "bin/example_apps/connectedcomponents file data/soc-Epinions1/soc-Epinions1.txt filetype edgelist"

  connectedcomponents-google:
    build: ./graphchi-c/
    command: "bin/example_apps/connectedcomponents file data/web-Google/web-Google.txt filetype edgelist"

  trianglecounting-facebook:
    build: ./graphchi-c/
    command: "bin/example_apps/trianglecounting file data/ego-Facebook/facebook_combined.txt filetype edgelist nshards 2"

  trianglecounting-epinions1:
    build: ./graphchi-c/
    command: "bin/example_apps/trianglecounting file data/soc-Epinions1/soc-Epinions1.txt filetype edgelist nshards 2"

  trianglecounting-google:
    build: ./graphchi-c/
    command: "bin/example_apps/trianglecounting file data/web-Google/web-Google.txt filetype edgelist nshards 2"
